### ISSUE TITLE
feat: 주요 엔티티 생성

### ISSUE THREAD

**Issue by yueunfive** [dnd-side-project/dnd-11th-5-backend#32]
## 개요
담당 도메인에 해당되는 주요 엔티티를 생성합니다.

## TODO
- [x] user 엔티티
- [x] festival 엔티티
- [x] review 엔티티
- [x] 수정사항 관련 DDL 작성

**Comment by punchdrunkard** [comment]
안그래도 엔티티 먼저 다 셋팅하자고 이야기하려했는데 굿입니다
